### ISSUE TITLE
BUG(Profile): deleting OF image gets me 404 page

### ISSUE THREAD

**Issue by poolsar42** [kubelt/rollupid#1581]
## What is the current behavior?

I deleted my background image on My profile /links/ page. And now I see 404 page that my account is yet to be unlocked

## What is the expected behavior?

To not see cover background image I suppose, but see that my account is unlocked

<img width="1720" alt="Screenshot 2023-02-06 at 12 32 40" src="https://user-images.githubusercontent.com/33105890/217043252-a125ee18-37b3-454f-8441-c8998a996644.png">

**Comment by Cosmin-Parvulescu** [comment]
I have opened up a PR #1589 that addresses this, however I think we should clarify what the intended behavior is from a product perspective. Currently the fix just updates trpc z schema check and allows profiles with no cover to generate OG images, but this might not be the desired behavior.
